#------------------------ Configuración BD ------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/farmacia
spring.datasource.username=admfarmacia
spring.datasource.password=pelota12
server.port=8087

aplicacion.url=http://localhost:4200