#------------------------ Configuración BD ------------------------
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/pdbfirma
spring.datasource.username=adm_firma
spring.datasource.password=Pelota12*


aplicacion.url=http://localhost:4200