#------------------------ Configuración BD ------------------------
spring.datasource.url=jdbc:oracle:thin:@200.7.160.21:1521/PDBFIRMA
spring.datasource.username=adm_firma
spring.datasource.password=Pelota12*


aplicacion.url=http://localhost:4200